---
language: python
python: "2.7"
sudo: required
install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' > ansible.cfg
script:
  - ansible-galaxy install geerlingguy.homebrew
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
