---
- name: Ensure that the {{ textual_package }} package is installed
  tags: textual
  homebrew_cask:
    name: "{{ textual_package|lower }}"
    state: present
  register: textual_homebrew_cask

- name: Attempting to apply {{ textual_package }} configurations
  tags: textual
  osx_defaults:
    domain: "{{ textual_domain }}"
    key: "{{ item.key|regex_replace('_', ' ') }}"
    state: "{{ item.value.state|default('present') }}"
    type: "{{ item.value.type }}"
    value: "{{ item.value.value }}"
  with_dict: "{{ textual_defaults }}"
  when:
    - item.key is defined
    - item.value.type is defined
    - item.value.value is defined
    - textual_defaults|length > 0
    - textual_homebrew_cask is success
...
